/robot/controller_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    FollowPath:
      acc_lim_theta: 0.5
      acc_lim_x: 0.2
      acc_lim_y: 0.0
      allow_init_with_backwards_motion: false
      cmd_angle_instead_rotvel: false
      control_look_ahead_poses: 1
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: true
      costmap_model:
        scale: 1.0
        sum_scores: false
      costmap_obstacles_behind_robot_dist: 1.0
      delete_detours_backwards: true
      detours_orientation_tolerance: 1.5707963267948966
      divergence_detection_enable: false
      divergence_detection_max_chi_squared: 10
      dt_hysteresis: 0.1
      dt_ref: 0.3
      dynamic_obstacle_inflation_dist: 0.1
      enable_homotopy_class_planning: false
      enable_multithreading: true
      exact_arc_length: false
      feasibility_check_lookahead_distance: -1.0
      feasibility_check_no_poses: 5
      footprint_model:
        type: polygon
        vertices: '[[0.361,-0.3065],[0.361,0.3065],[-0.361,0.3065],[-0.361,-0.3065]]'
      force_reinit_new_goal_angular: 1.5707963267948966
      force_reinit_new_goal_dist: 1.0
      free_goal_vel: false
      global_plan_overwrite_orientation: true
      global_plan_prune_distance: 1.0
      global_plan_viapoint_sep: 0.5
      h_signature_prescaler: 1.0
      h_signature_threshold: 0.1
      include_costmap_obstacles: false
      include_dynamic_obstacles: true
      inflation_dist: 0.15
      is_footprint_dynamic: false
      legacy_obstacle_association: false
      length_start_orientation_vector: 0.4
      max_global_plan_lookahead_dist: 10.0
      max_number_classes: 4
      max_ratio_detours_duration_best_duration: 3.0
      max_samples: 500
      max_vel_theta: 0.6
      max_vel_x: 0.25
      max_vel_x_backwards: 0.15
      max_vel_y: 0.0
      min_obstacle_dist: 0.03
      min_resolution_collision_check_angular: 3.141592653589793
      min_samples: 3
      min_turning_radius: 0.0
      no_inner_iterations: 5
      no_outer_iterations: 4
      obstacle_association_cutoff_factor: 5.0
      obstacle_association_force_inclusion_factor: 1.5
      obstacle_cost_exponent: 1.0
      obstacle_heading_threshold: 0.45
      obstacle_keypoint_offset: 0.1
      obstacle_poses_affected: 30
      obstacle_proximity_lower_bound: 0.0
      obstacle_proximity_ratio_max_vel: 1.0
      obstacle_proximity_upper_bound: 0.5
      odom_topic: odom
      optimization_activate: true
      optimization_verbose: false
      oscillation_filter_duration: 10.0
      oscillation_omega_eps: 0.1
      oscillation_recovery: true
      oscillation_recovery_min_duration: 10.0
      oscillation_v_eps: 0.1
      penalty_epsilon: 0.1
      plugin: teb_local_planner::TebLocalPlannerROS
      publish_feedback: false
      roadmap_graph_area_length_scale: 1.0
      roadmap_graph_area_width: 6.0
      roadmap_graph_samples: 15
      selection_alternative_time_cost: false
      selection_cost_hysteresis: 1.0
      selection_dropping_probability: 0.0
      selection_obst_cost_scale: 1.0
      selection_prefer_initial_plan: 4.0
      selection_viapoint_cost_scale: 1.0
      shrink_horizon_backup: true
      shrink_horizon_min_duration: 10.0
      simple_exploration: false
      switching_blocking_period: 0.0
      teb_autosize: 1.0
      via_points_ordered: false
      viapoints_all_candidates: true
      visualize_hc_graph: false
      visualize_with_time_as_z_axis_scale: 0.0
      weight_acc_lim_theta: 1.0
      weight_acc_lim_x: 1.0
      weight_acc_lim_y: 0.0
      weight_adapt_factor: 2.0
      weight_dynamic_obstacle: 50.0
      weight_dynamic_obstacle_inflation: 0.1
      weight_inflation: 1.0
      weight_kinematics_forward_drive: 1000.0
      weight_kinematics_nh: 10000.0
      weight_kinematics_turning_radius: 0.0
      weight_max_vel_theta: 20.0
      weight_max_vel_x: 900.0
      weight_max_vel_y: 0.0
      weight_obstacle: 60.0
      weight_optimaltime: 60.0
      weight_prefer_rotdir: 50.0
      weight_shortest_path: 0.0
      weight_velocity_obstacle_ratio: 0.0
      weight_viapoint: 100.0
      wheelbase: 0.0
    controller_frequency: 20.0
    controller_plugins:
    - FollowPath
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.1
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    odom_topic: /robot/robotnik_base_control/odom
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
    progress_checker_plugin: progress_checker
    speed_limit_topic: speed_limit
    use_sim_time: false

